kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "app-module-build" 
spec:
  source: 
    git:
      uri: "https://github.com/kavish-p/openshift-demo-app"
    contextDir: "words"
  strategy: 
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "kavish-app:latest"